### ISSUE TITLE
New interlanguage link synchronization solution

### ISSUE THREAD

**Issue by kynikos** [kynikos/wiki-monkey#148]
https://wiki.archlinux.org/index.php/Talk:Wiki_Monkey#Improvements_to_the_interlanguage_syncing_algorithm

**Comment by lahwaacz** [comment]
Considering #210, this issue could be closed since there is [update-interlanguage-links.py](https://github.com/lahwaacz/wiki-scripts/blob/master/update-interlanguage-links.py) now, which uses even better algorithm than the one proposed in the talk linked above.

**Comment by kynikos** [comment]
Indeed, your bot has proved very efficient at this task! Thanks
