### ISSUE TITLE
Bot plugins: add assert=bot to the edit query?

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#212]
Since MW-1.23 there is an easy way to make sure that the bot is logged in and that the account is a bot account: http://www.mediawiki.org/wiki/API:Assert
Maybe Wiki Monkey's bot plugins should use this method to avoid being run from normal user accounts?

**Comment by kynikos** [comment]
Well, this feature may indeed be useful in some cases, but Wiki Monkey's bot is more designed for quick fixes to short lists of articles, so I think also normal users should be able to use its plugins. Yes, I have used WM also for big jobs in the past, but a standalone framework like wiki-scripts is better suited for those scenarios.

**Comment by lahwaacz** [comment]
That's a good point, sorry...
