### ISSUE TITLE
Redirects over interwiki links

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#213]
Wiki Monkey can't deal with redirects over interwiki links, e.g. [this one](https://wiki.archlinux.org/index.php?title=Core_Utilities_(Espa%C3%B1ol)&diff=370090&oldid=370048). Before I fixed it, the page redirected to [this url](https://wiki.archlinux.org/index.php/Core_utilities_(Espa%C3%B1ol)?rdfrom=https%3A%2F%2Fwiki.archlinux.org%2Findex.php%3Ftitle%3DCore_Utilities_%28Espa%25C3%25B1ol%29%26redirect%3Dno) and Wiki Monkey choked when I wanted to [sort interlanguage links](https://wiki.archlinux.org/index.php?title=Core_utilities&diff=370091&oldid=370045) on other page.
Just thought I'd let you know...

**Comment by kynikos** [comment]
Thanks, it's fixed now in the develop branch: this should be a rather rare bug, so I don't feel the need to do a release, I think you're using your own fork so you can pull the patch, right?
Actually the fix consists in just showing a warning and continuing the execution, leaving the offending interlanguage link as it is: if the redirect uses a real external interwiki link, its target couldn't be checked for interlanguage links anyway; internal/fake interwiki links are peculiar to the ArchWiki, and shouldn't be used in redirects in the first place, so I think issuing a warning is the proper way to fix this :)

**Comment by lahwaacz** [comment]
Agreed, warning is just fine. Unfortunately there is no way to test this :D and I think there will be many releases before I come across this issue again.
