### ISSUE TITLE
Don't fix headings when editing a section

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#215]
The "Fix headings" plugin/button should just blow up when a section is being edited, otherwise executing all the "Text plugins" will mess up the page.

Since all pages on ArchWiki are supposed to be categorized and the header is fixed before the headings in the "Text plugins" row, checking if the textarea starts with `[[Category:` might do the trick.

**Comment by kynikos** [comment]
Nah, the Editor module could already recognize section editors more reliably, it's been very easy to make the plugin work as expected when editing a section (available in the develop branch). Thanks for reporting as always!

**Comment by lahwaacz** [comment]
Well, now it blows up properly only when the edited section has at least one subsection. For example if you test it on [Mailgraph#Installation](https://wiki.archlinux.org/index.php/Mailgraph#Installation), `WM.Parser.findSectionHeadings` returns
``` json
{"sections":[{"line":"== Installation ==","rawheading":" Installation ","heading":"Installation","cleanheading":"Installation","level":2,"tocLevel":1,"index":0,"length0":18,"length1":18}],"minLevel":0,"maxTocLevel":0}
```
and then `increaseLevel = info.minLevel - 1` assigns `-1` so all the `=` chars are actually stripped... But this seems to be a bug in the parser, so you are probably right that testing the `section` URI parameter is more reliable ;)

**Comment by kynikos** [comment]
Yep, definitely a bug in `Parser`, fixed in `develop`. While testing (more thoroughly this time) it turned out that `section` in the url is lost when requesting the diff or the preview, so I've also changed `Editor.isSection` to a more reliable test. Thanks again :)
