### ISSUE TITLE
Plugin to move a category

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#217]
Since one of the recent MediaWiki versions (1.23/24/25), category pages can be moved, but the pages are not automatically recategorized. When I previously moved a category, I used Wiki Monkey's SimpleReplace plugin, which is obviously very error-prone. The task itself can be automated, but of course needs to be thoroughly tested. I could do it in wiki-scripts (of course interactively), but doing it in the browser would be even better. Could you start working on this?

A note for the future: the original category should be redirected to the new one and deleted only after synchronizing the interlanguage links.

**Comment by lahwaacz** [comment]
Actually, they can be recategorized automatically from a wiki-script based on the redirect that will be left behind after moving the category page interactively in the MediaWiki interface. I should have thought of this earlier...

**Comment by kynikos** [comment]
Besides, this was duplicating #185 :) I'll leave that open because it should be easy to implement here too anyway.

**Comment by lahwaacz** [comment]
I was actually looking for that one before opening this, but did not find it :-/
