### ISSUE TITLE
Hide hidden categories in the Table of contents

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#224]
I guess the hidden categories should also be hidden on the [Table of contents](https://wiki.archlinux.org/index.php?title=Table_of_contents&diff=next&oldid=414851) page. You can get the hidden categories in https://wiki.archlinux.org/api.php?action=query&list=allcategories&acprop=hidden&aclimit=max but have to manually filter the `hidden` attribute. Maybe you're already using a query where adding `acprop=hidden` or `clprop=hidden` would be enough?

**Comment by kynikos** [comment]
All done, cheers

**Comment by kynikos** [comment]
Reopening, there's still a bug... https://wiki.archlinux.org/index.php?title=Table_of_contents_%28%ED%95%9C%EA%B5%AD%EC%96%B4%29&diff=416041&oldid=411628
