### ISSUE TITLE
Standalone version: minification bug

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#225]
The [standalone](https://github.com/kynikos/wiki-monkey/blob/master/scripts/WikiMonkey-ArchWiki-standalone.user.js) version looks funny: the first 4 lines contain something minified, but the rest of the file (9022 lines) are unminified.

**Comment by lahwaacz** [comment]
Oh, it's the minified jQuery, never mind then...

**Comment by kynikos** [comment]
:)
Keep in mind that I'm in the process of rewriting the whole application in CoffeeScript, I don't know what exactly you're trying to do, but don't waste too much time on that code...

**Comment by lahwaacz** [comment]
Nah, I was just going to see if it actually works, and it does (except for the configuration, see #226), so no code wasted.
