### ISSUE TITLE
Error after manual update to 5.0.3

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#233]
Hi, I get this error after I manually upgraded Wiki Monkey to 5.0.3:
```
Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at shouldCheck (WikiMonkey-ArchWiki.min.js:52725)
    at module.exports.upgradePeriodical (WikiMonkey-ArchWiki.min.js:52662)
    at WikiMonkey.init (WikiMonkey-ArchWiki.min.js:50046)
    at WikiMonkey-ArchWiki.min.js:49817
shouldCheck @ WikiMonkey-ArchWiki.min.js:52725
module.exports.upgradePeriodical @ WikiMonkey-ArchWiki.min.js:52662
init @ WikiMonkey-ArchWiki.min.js:50046
(anonymous) @ WikiMonkey-ArchWiki.min.js:49817
Promise.then (async)
WikiMonkey @ WikiMonkey-ArchWiki.min.js:49816
initWM @ WikiMonkey-ArchWiki.min.js:52600
PreInit @ WikiMonkey-ArchWiki.min.js:52592
426../lib/PreInit @ WikiMonkey-ArchWiki.min.js:46248
o @ WikiMonkey-ArchWiki.min.js:236
r @ WikiMonkey-ArchWiki.min.js:236
(anonymous) @ WikiMonkey-ArchWiki.min.js:236
```

**Comment by kynikos** [comment]
Hi, thanks, sorry, I'm away from my main development environment and didn't test this update well, I basically just threw a quick fix there with my fingers crossed... Unfortunately MediaWiki 1.33 also apparently broke at least another API module (mw.storage) (or they deprecated it without warning? It's still documented at https://doc.wikimedia.org/mediawiki-core/master/js/#!/api/mw.storage though, and can't find any related bug reports). This will be easy to work around, but at this stage I can't take for granted that there aren't any more breaking changes, I need to take some time to test it properly, apologies :'(

**Comment by kynikos** [comment]
Note to self: ...or perhaps now all (sub)modules have to be imported explicitly in https://github.com/kynikos/wiki-monkey/blob/master/src/index.js#L19

**Comment by lahwaacz** [comment]
No problem, take your time...

Note that the error does not appear on the Special:RecentChanges page or when editing pages, but only when viewing normal pages.
