### ISSUE TITLE
Watchlist indicator

### ISSUE THREAD

**Issue by lahwaacz** [kynikos/wiki-monkey#238]
Would it be possible to add an indicator next to the "Watchlist" link in the wiki (top-right corner) so that I can easily see how many "unread" pages are in my watchlist? Often when I open a diff and click through the changes, they still remain as "unread" in the watchlist, so I must manually "Mark all pages visited", otherwise new notification emails will not arrive...

**Comment by kynikos** [comment]
Very likely possible if there's an API call for that (and quicker to implement if you can find an example for me instead of waiting for me to find the time :P )

If there's also a call to mark all pages visited, I can add a shortcut to it too!

**Comment by lahwaacz** [comment]
Yes, MediaWiki API has a [watchlist module](https://www.mediawiki.org/wiki/Special:MyLanguage/API:Watchlist). Basically pass `wlshow=unread` and count the number of results:
https://wiki.archlinux.org/api.php?action=query&list=watchlist&wllimit=max&wlnamespace=*&wlprop=ids&wlshow=unread

As for marking all pages visited, I did not find an action for this in the API...

**Comment by kynikos** [comment]
Thanks! I've also quickly tried the mark-all-pages button and it sends a request like this: https://wiki.archlinux.org/api.php?action=setnotificationtimestamp&format=json&formatversion=2&entirewatchlist=true&token=[token] which should be documented at https://www.mediawiki.org/wiki/API:Setnotificationtimestamp

So if you think it's helpful I guess I can try that as well while I'm at it :)

**Comment by lahwaacz** [comment]
Oh, great! It would be one less click for me, so I think that I'd quickly get used to it, but I'm not sure if many people would actually use this mark-all-as-read button...

**Comment by kynikos** [comment]
It can be triggered by a link anchored on the number itself, so it doesn't take any extra space ^^

Anyway I was thinking that the counter query itself should only be triggered manually by default, to minimise the number of queries on page load, and there should be an option to run it automatically, and maybe only on specific pages such as diffs... Just some ideas, it has to wait until the weekend anyway...

**Comment by lahwaacz** [comment]
Oh, right... Maybe the result of the query should be cached in the local storage and the query itself should be run only every X minutes, and no sooner than Y seconds after the page was loaded? That way loading a buch of pages would still result in at most 1 extra query (if the pages don't start the query before something else finishes it). But I don't know how much work it would be to implement this behaviour, do whatever is easy for you, even running it automatically only on a limited set of pages like diffs would work for me...

**Comment by kynikos** [comment]
Cool suggestions, thanks, it should work now (version 5.2.1), but:
* For some reason the automated version update to 5.2.1 seemed to fail for me, I haven't had the time to find the problem yet, you may have to upgrade manually
* The watchlist number can't be in a superscript because it messes up the list of links, so I've put it in a subscript
* By default the count is cached for 1800s (the "X" interval), you can change it by adding e.g. `Watchlist: {minQueryInterval: 60}` to your `wikiMonkeyConfig`
* I've left the "Y" delay out, as it would only delay races, not prevent them, there isn't much to do against them besides attempting to implement some complicated IPC locks, I'll KISS this one :)

**Comment by lahwaacz** [comment]
Cool, it works, thanks! As for the formatting, maybe it would be better to use some brackets? E.g. `Watchlist(13)` or `Watchlist (13)` or `Watchlist [13]` (Wiki Monkey uses square brackets in other parts of the interface too). I wouldn't care if the brackets themselves were black or blue...

**Comment by kynikos** [comment]
Well, I had the prejudice that with brackets it would look too intrusive, so I didn't even try it honestly, but I've just tried and it doesn't look bad at all, I may reconsider.

I'm also curious though, did the automated upgrade to 5.2.1 work for you? I think I've discovered why it didn't work for me, but those who skipped 5.2.0 shouldn't have been affected if I got it right.

**Comment by lahwaacz** [comment]
I don' know if the automated upgrade works, I clicked the buttons manually too soon :(

**Comment by kynikos** [comment]
If you don't know it means it worked, otherwise you'd have had to edit your common.js manually ;) Cheers, I'll leave the brackets patch until next weekend.
