### ISSUE TITLE
Running "Sync interlanguage links" removes all on-wiki language links

### ISSUE THREAD

**Issue by kattjevfel** [kynikos/wiki-monkey#249]
Possibly due to #248, I'm running Version: 5.3.2 (standalone).
![Screenshot 2021-05-13 at 20-29-44 Editing Main page (Svenska) - ArchWiki](https://user-images.githubusercontent.com/6226312/118170296-37a33100-b42a-11eb-80e7-94040527b1da.png)

**Comment by kynikos** [comment]
Oh, thanks for the report... I'm going to blame it on the testing team :)

**Comment by kynikos** [comment]
Fixed, it wasn't due to #248, but to an upstream breaking change and some modifications to ArchWiki's configuration.
