### ISSUE TITLE
Make server able to bind to any server name

### ISSUE THREAD

**Issue by kattjevfel** [kynikos/wiki-monkey#252]
Not 100% about my terminology here, but as it is right now I have to set the `host` in ~/.config/wiki-monkey/server.conf to the IP of my  LXC container running wiki-monkey, this is a problem when running a reverse proxy, as I try to access it via example.com, but the .js still wants to connect to that internal IP.

If I could just set it to example.com in server.conf, but still connect to it from 192.168.1.123, that'd solve the issue.

**Comment by kynikos** [comment]
Perhaps I have a solution, but are you willing to help me test it a little on your system?

On the server machine, can you sudo-edit `/usr/share/wiki-monkey/WikiMonkey-ArchWiki.min.js` (or `WikiMonkey-ArchWiki.js` if you're using the non-minified client) and **prepend** the following line to the file (of course adapt it to your needs):

```
var _WIKI_MONKEY_SERVER_URL = "https://www.example.com/";
```

It wouldn't be a permanent solution, but does it do what you want? If so, keep the file like that, and for the next versions I'll implement something more proper.

**Comment by kattjevfel** [comment]
It seems the original _WIKI_MONKEY_SERVER_URL gets stuck at the top no matter what like so:

```
var _WIKI_MONKEY_SERVER_URL = "https://192.168.1.100:13502/";

var _WIKI_MONKEY_SERVER_URL = "https://users.lewd.se/katt/wiki-monkey/";

/*! For license information please see WikiMonkey-ArchWiki.min.js.LICENSE.txt */
```

**Comment by kynikos** [comment]
Yeah the final fix is going to be in static.py, but prepending the _WIKI_MONKEY_SERVER_URL line in your js file should have the same effect: the original line should simply get overridden by the one below. Are you sure you didn't test it with a cached version that still didn't have the updated variable?

**Comment by kattjevfel** [comment]
At the time I had only added it to `ArchWiki.min.js`, and after I restarted the service and refreshed the page I got what is shown above.

If I had not refreshed I would not have gotten that much. When I went and edited `static.py` I instead got double of the one I had edited in, so I removed the one from `ArchWiki.min.js` to get a "clean" result.

only `ArchWiki.min.js` edited:
![2021-06-23_12-48-27](https://user-images.githubusercontent.com/6226312/123139205-3ff18180-d456-11eb-8f74-00e1e7300098.png)

both `ArchWiki.min.js` and `static.py` edited:
![2021-06-23_19-08-22](https://user-images.githubusercontent.com/6226312/123139367-6e6f5c80-d456-11eb-97ab-172d1d1b826a.png)

`ArchWiki.min.js` restored to default but `static.py` edited:
![2021-06-23_19-09-11](https://user-images.githubusercontent.com/6226312/123139488-8d6dee80-d456-11eb-851f-a33cb193d039.png)

**Comment by kynikos** [comment]
You don't need a "clean" result, the double entry is expected if you edit the js file, what counts is only the second entry, i.e. the one that you manually hardcode in the js file; the first variable definition (prepended by the server) gets overridden by yours. Anyway, it's only a temporary solution, what's important is that you found a way to make it work, which means that that is the way to fix the problem, so I'll give you a new configuration option in the next release, since of course all those manual changes will be reverted when you upgrade the installed package.

**Comment by kattjevfel** [comment]
I kinda just assumed the top one would take priority as it was "found" first but I never tried it. Good to hear nevertheless and thank you for working on this!

**Comment by kynikos** [comment]
Thank you for trying the software and reporting issues instead of giving up :)

**Comment by kynikos** [comment]
After upgrading to 5.5.0, you should be able to set the url as the value of a new `proxy_url` option in your server configuration file (probably `~/.config/wiki-monkey/server.conf`):

    proxy_url = https://users.lewd.se/katt/wiki-monkey/

**Comment by kattjevfel** [comment]
Seems to work great, just had install gunicorn and change my nginx settings.

**Comment by kynikos** [comment]
Thanks for confirming that it works!

Indeed I forgot to mention that using Gunicorn is recommended now, especially if exposing the service to the public web.

I'm curious though, the application should have still defaulted to using Flask's server when you didn't have Gunicorn installed; did you received an error instead?

I also forgot to document the new `workers` option with which you can increase the number of [worker processes](https://docs.gunicorn.org/en/stable/settings.html#worker-processes) if you want; I've updated the docs now.

**Comment by kattjevfel** [comment]
> I'm curious though, the application should have still defaulted to using Flask's server when you didn't have Gunicorn installed; did you received an error instead?
> 
Yeah, I received a traceback after I had set proxy_url:
```
Traceback (most recent call last):
  File "/usr/bin/wiki-monkey", line 33, in <module>
    sys.exit(load_entry_point('wiki-monkey==5.5.0', 'console_scripts', 'wiki-monkey')())
  File "/usr/lib/python3.9/site-packages/wiki_monkey/main.py", line 205, in main
    app.run(default_configfile, base_conf, argparser.parse_args())
  File "/usr/lib/python3.9/site-packages/wiki_monkey/lib/app.py", line 134, in run
    models, api, static = _pre_run(True)
  File "/usr/lib/python3.9/site-packages/wiki_monkey/lib/app.py", line 53, in _pre_run
    from . import models, api, static
  File "/usr/lib/python3.9/site-packages/wiki_monkey/lib/api/__init__.py", line 19, in <module>
    from flask_rip import IMPLICIT, API
  File "/usr/lib/python3.9/site-packages/flask_rip.py", line 20, in <module>
    from apispec_webframeworks.flask import FlaskPlugin
  File "/usr/lib/python3.9/site-packages/apispec_webframeworks/__init__.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gunicorn' distribution was not found and is required by wiki-monkey
```

My config:
```ini
host = 192.168.1.100
port = 13502
origins =
proxy_url = https://users.lewd.se/katt/wiki-monkey/
db_path = /home/katt/.local/share/wiki-monkey/db.sqlite
client_conf = /home/katt/.config/wiki-monkey/client.json
user_script_dir = /usr/share/wiki-monkey/

[archwiki]
origins = https://wiki.archlinux.org

[wikipedia]
origins = https://en.wikipedia.org
```

Either way it all works fine with gunicorn and all is well.

> I also forgot to document the new `workers` option with which you can increase the number of [worker processes](https://docs.gunicorn.org/en/stable/settings.html#worker-processes) if you want; I've updated the docs now.

Sweet, might look into that if I ever get anything more powerful than a dual-core :p

**Comment by kynikos** [comment]
Thanks for sharing the traceback, maybe one day I'll figure out how to reproduce it, but at least the error message is pretty clear and helpful :)
