### ISSUE TITLE
Recent change to archwiki links broken

### ISSUE THREAD

**Issue by kattjevfel** [kynikos/wiki-monkey#257]
As of updating to wiki-monkey v.5.5.1, when running *Fix external links* instead it breaks in quite an interesting way:

Original: `[https://wiki.archlinux.org/title/Solid_state_drive#TRIM TRIM]`
After: `[[title|Solid_state_drive#TRIM]]`

Normally it should've been something like `[[Solid_state_drive#TRIM|TRIM]]`

Page to test this on (in *Enabling TRIM* section): https://wiki.archlinux.org/index.php?title=ZFS&action=edit&oldid=704704

**Comment by lahwaacz** [comment]
Oh yeah, I messed up in https://github.com/kynikos/wiki-monkey/commit/24e4526462e9a508c307947471785e3326812b92. The numbers in `txt.replace` need to be incremented...

**Comment by kynikos** [comment]
Thanks guys for doing the beta testing and the patching!!! 🥰
Oneday™ I will implement unit testing and these things won't happen anymore 😌
