### ISSUE TITLE
Watchlist plugin doesn't look right with the new Vector theme's user menu

### ISSUE THREAD

**Issue by nl6720** [kynikos/wiki-monkey#259]
With [user menu](https://www.mediawiki.org/wiki/Reading/Web/Desktop_Improvements/Features/User_menu) now being enabled by default for the new Vector theme, Wiki Monkey's watchlist plugin doesn't look right.

The square brackets and the number between them are all in separate lines.

![Screenshot 2021-12-21 at 15-01-46 Recent changes - ArchWiki](https://user-images.githubusercontent.com/17086862/146934685-23027212-bc6d-4649-9e3f-ad2e6f2ef81e.png)

**Comment by kynikos** [comment]
Ouch, thanks, there's some nasty css trickery going on in there now... I could make it work again I guess, but is the unread counter still useful inside the disappearing menu? Should I move it back outside so it's always visible? (it would actually be easier for me than reassembling that menu, I admit) I more or less notoriously don't use the watchlist, as I patrol all changes every day, so I'd need some feedback from you guys first ^^

**Comment by nl6720** [comment]
Yeah, I think having it outside is probably more useful.
